#%RAML 1.0 DataType
type: object
properties:
  createEmployeeById:
    description: employee creation details
    type: object
    properties:
      id:
        type: integer
        example: 123
      telephone:
        type: string
        example: "1234567895"
          
          
          